<?php $payments = $this->getPaypoints()?>
<?php if(count($payments) == 0):?>
	<div class="notice"><?php echo Mage::helper('kyash')->__('No shops available')?></div>
<?php else:?>
    <table width="100%" border="0" cellspacing="0" cellpadding="0" id="payment_points" class="data-table">
    	<colgroup>
            <col style="width:220px;">
            <col>
        </colgroup>
        <thead>
            <tr>
                <th style="text-align:left"><?php echo Mage::helper('kyash')->__('Shop Name')?></th>
                <th style="text-align:left"><?php echo Mage::helper('kyash')->__('Address')?></th>
            </tr>
        </thead>
        <tbody>
        <?php $index = 1; ?>
		<?php foreach($payments as $payment):?>
            <tr class="<?php echo ((($index++)%2) == 0 ? "even" : "odd")?>">
                <td  style="text-align:left"><?php echo $payment['shop_name']?></td>
                <td style="text-align:left"><?php echo $payment['address']?></td>
            </tr>
        <?php endforeach;?>
        <tbody>
    </table>
<?php endif;?>