<?php
$postcode = $this->getPostcode();
?>
<div style="display: none;" id="see_nearby_shops_container">
    <kyash:code merchant_id="<?php echo Mage::helper('kyash')->getAuthId()?>" postal_code="<?php echo $postcode ?>"></kyash:code>
</div>
<p style="display: none;" id="kyash_payment_instructions">Product will be sent to the shipping address only after payment. If order is cancelled or not delivered, you can avail refund as per our policies.</p>
