<?php 
$postcode = $this->getPostcode();
if(empty($postcode))
	$postcode = 'Enter Pincode';
?>
<span id="kyash_postcode_payment">
    <a href="javascript:void(0);" onclick="openShops('<?php echo $this->getUrl('kyash/index/getPaymentPoints', array('key'=>false))?>','<?php echo Mage::getBaseUrl('skin').'frontend/default/default/images/opc-ajax-loader.gif';?>')" id="kyash_open">
    <?php echo Mage::helper('kyash')->__('See nearby shops')?>
    </a>
   
    <span id="kyash_postcode_payment_sub">
        <input type="text" class="input-text" id="kyash_postcode" value="<?php echo $postcode ?>" maxlength="12" />
        <button id="kyash_postcode_button" onclick="pullNearByShops('<?php echo $this->getUrl('kyash/index/getPaymentPoints', array('key'=>false))?>','<?php echo Mage::getBaseUrl('skin').'frontend/default/default/images/opc-ajax-loader.gif';?>')" class="button" type="button">
    		<span><span><?php echo Mage::helper('kyash')->__('See Nearby Shops')?></span></span>
   		</button>
        <a href="javascript:void(0);" onclick="closeShops()" id="kyash_close" style="float:right">
			<?php echo Mage::helper('kyash')->__('X')?>
        </a>
    </span>
</span>
<div style="display: none" id="see_nearby_shops_container">
</div>