<?php if ($order = $this->getOrder()):?>
<?php 
$postcode = $this->getPostcode();
if(empty($postcode))
	$postcode = 'Enter Pincode';

$dateTime = new DateTime();
$dateTime->setTimestamp($order->getKyashExpires());
$dateTime->setTimeZone(new DateTimeZone('Asia/Kolkata'));
$kc_expires_on = $dateTime->format("j M Y, g:i A");
?>
<div style="" id="see_nearby_shops_container2">
    <script src="//secure.kyash.in/outlets.js"></script>
    <kyash:code div="#see_nearby_shops_container" merchant_id="<?php echo Mage::helper('kyash')->getAuthId()?>" postal_code="<?php echo $postcode ?>" kyash_code="<?php echo $order->getKyashCode()?>"></kyash:code>
</div>
<?php endif;?>